wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      4: 3.7.9
      5: 0.10.27
      8:
      - 1
      - 3
      - 5
save_path:
  desc: null
  value: model_save\19_May_202103_35PM_model.pth
